### ISSUE TITLE
bug in check digit computation

### ISSUE THREAD

**Issue by Manu1400** [michaelwittig/node-isin-validator#1]
1/ Install package with command `npm i cinovo-isin-validator` (-> i have the lasted version installed)
2/ Package is installed, i use it in this code:
```javascript
const validator = require("cinovo-isin-validator")

// first example: https://www.wikidata.org/wiki/Property:P946#P1855
const examples = [
  'GB00B42CTW68', // value from example of Wikidata Property:P946 
  'US0358140123', // value in webpage https://www.isin.net/isin-directory/
  'CA26842Y1025', // value in webpage https://www.isin.net/isin-directory/
  'US68389X1054', // value from Q19900, in Property:P946
]

const options = {} //{checkCheckDigit: false}

examples.forEach(function(example) {
  validator(example, function(err) {
  	if (err) {
  		console.log("ISIN is invalid! value: " + example, err)
  	} else {
  		console.log("ISIN is fine!")
  	}
  }, options)

})
```
3/ run code with `node <filename>.js`

```
ISIN is fine!
ISIN is invalid! value: US0358140123 Error: Check digit is wrong
    at module.exports (/Users/emmanuel/wikidata-api-more/node_modules/cinovo-isin-validator/index.js:199:25)
    at /Users/emmanuel/wikidata-api-more/modules/id-ISIN/isin.js:22:3
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/emmanuel/wikidata-api-more/modules/id-ISIN/isin.js:21:10)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
ISIN is fine!
ISIN is fine!
```

"US0358140123" exist, see : https://www.isin.net/isin-directory/isin-profile/?isin=US0358140123

result of command `make test`:

```
jslint

./index.js is OK.

./test/isin.js is OK.
mocha
(node:73604) [DEP0006] DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.

  ․․․․․․․․․․․․․․․․․․․․․․

  22 passing (24ms)


circular
No circular dependencies found!
test
```

**Comment by Manu1400** [comment]
same issue on https://www.isincheck.com/?isin=US0358140123 : 
> ISIN is not correct. (Checksum should be 9)

**Comment by michaelwittig** [comment]
The ISIN does not follow the specification.

You can disable the check digit validation by setting `checkCheckDigit`to false as your code shows.
